from app.models import db, Stock, Tag, environment, SCHEMA
from sqlalchemy.sql import text


def seed_stocks():
    stocks = [
        {
            "name": "Apple",
            "symbol": "AAPL",
            "description": "A globally renowned technology company that has revolutionized consumer electronics with innovative products such as the iPhone, iPad, Mac computers, and Apple Watch. It also offers software services like iOS, macOS, and subscription platforms like Apple Music and iCloud.",
            "price": 150.0,
            "initial_price": 150.0,
            "total_shares": int(100000000 / 150.0),
            "remaining_shares": int(100000000 / 150.0),
            "tag_id": 1,
        },
        {
            "name": "Tesla",
            "symbol": "TSLA",
            "description": "A leader in the electric vehicle market, known for its cutting-edge designs and technologies in cars like the Model S, Model 3, and Model Y. Tesla also develops clean energy solutions, including solar panels and energy storage products like the Powerwall.",
            "price": 700.0,
            "initial_price": 700.0,
            "total_shares": int(50000000 / 700.0),
            "remaining_shares": int(50000000 / 700.0),
            "tag_id": 2,
        },
        {
            "name": "Amazon",
            "symbol": "AMZN",
            "description": "The world's largest online retailer, providing a vast range of products and services. It is also a dominant player in cloud computing through Amazon Web Services (AWS), enabling businesses to operate efficiently.",
            "price": 3300.0,
            "initial_price": 3300.0,
            "total_shares": int(150000000 / 3300.0),
            "remaining_shares": int(150000000 / 3300.0),
            "tag_id": 1,
        },
        {
            "name": "Google",
            "symbol": "GOOGL",
            "description": "A cornerstone of the digital age, specializing in internet search, digital advertising, and a suite of products like Gmail, Google Maps, and the Android operating system. It also explores AI, cloud computing, and hardware innovations.",
            "price": 2800.0,
            "initial_price": 2800.0,
            "total_shares": int(120000000 / 2800.0),
            "remaining_shares": int(120000000 / 2800.0),
            "tag_id": 1,
        },
        {
            "name": "Microsoft",
            "symbol": "MSFT",
            "description": "A software powerhouse known for Windows, Office 365, and its Azure cloud services. It also ventures into hardware with products like Surface devices and gaming through Xbox.",
            "price": 320.0,
            "initial_price": 320.0,
            "total_shares": int(110000000 / 320.0),
            "remaining_shares": int(110000000 / 320.0),
            "tag_id": 1,
        },
        {
            "name": "Meta",
            "symbol": "META",
            "description": "A social media and technology company previously known as Facebook. It operates platforms like Facebook, Instagram, and WhatsApp, while investing heavily in augmented reality and virtual reality to build the metaverse.",
            "price": 340.0,
            "initial_price": 340.0,
            "total_shares": int(90000000 / 340.0),
            "remaining_shares": int(90000000 / 340.0),
            "tag_id": 1,
        },
        {
            "name": "NVIDIA",
            "symbol": "NVDA",
            "description": "A leader in graphics processing units (GPUs) for gaming, professional visualization, and AI computing. Its technology is a backbone for high-performance computing, autonomous vehicles, and data centers.I",
            "price": 500.0,
            "initial_price": 500.0,
            "total_shares": int(70000000 / 500.0),
            "remaining_shares": int(70000000 / 500.0),
            "tag_id": 1,
        },
        {
            "name": "Netflix",
            "symbol": "NFLX",
            "description": "A pioneering streaming service offering a vast library of movies, TV shows, and original content. It has transformed how audiences consume media with its on-demand subscription model.",
            "price": 400.0,
            "initial_price": 400.0,
            "total_shares": int(60000000 / 400.0),
            "remaining_shares": int(60000000 / 400.0),
            "tag_id": 3,
        },
        {
            "name": "Disney",
            "symbol": "DIS",
            "description": "A world-famous entertainment company producing animated and live-action films, TV content, and operating theme parks like Disneyland and Disney World. It also owns Marvel, Star Wars, and National Geographic.",
            "price": 120.0,
            "initial_price": 120.0,
            "total_shares": int(80000000 / 120.0),
            "remaining_shares": int(80000000 / 120.0),
            "tag_id": 3,
        },
        {
            "name": "Coca-Cola",
            "symbol": "KO",
            "description": "A beverage giant recognized globally for its flagship Coca-Cola drink, along with an extensive portfolio of sparkling and still beverages, including Sprite, Fanta, and Dasani water.",
            "price": 60.0,
            "initial_price": 60.0,
            "total_shares": int(60000000 / 60.0),
            "remaining_shares": int(60000000 / 60.0),
            "tag_id": 4,
        },
        {
            "name": "PepsiCo",
            "symbol": "PEP",
            "description": "A diversified food and beverage company with brands like Pepsi, Gatorade, Lay's, and Quaker Oats. It balances its portfolio with a focus on healthy and sustainable products.",
            "price": 150.0,
            "initial_price": 150.0,
            "total_shares": int(65000000 / 150.0),
            "remaining_shares": int(65000000 / 150.0),
            "tag_id": 4,
        },
        {
            "name": "Exxon Mobil",
            "symbol": "XOM",
            "description": "One of the world's largest oil and gas companies, involved in the exploration, production, refining, and distribution of energy resources. It also invests in renewable energy technologies.",
            "price": 110.0,
            "initial_price": 110.0,
            "total_shares": int(100000000 / 110.0),
            "remaining_shares": int(100000000 / 110.0),
            "tag_id": 5,
        },
        {
            "name": "Chevron",
            "symbol": "CVX",
            "description": "A leading energy corporation focusing on oil, gas, and alternative energy. It is known for innovation in energy efficiency and advanced technologies in the energy sector.",
            "price": 130.0,
            "initial_price": 130.0,
            "total_shares": int(95000000 / 130.0),
            "remaining_shares": int(95000000 / 130.0),
            "tag_id": 5,
        },
        {
            "name": "Intel",
            "symbol": "INTC",
            "description": "A pioneer in semiconductor manufacturing, designing high-performance microprocessors and technologies that power computers, data centers, and AI applications.",
            "price": 40.0,
            "initial_price": 40.0,
            "total_shares": int(40000000 / 40.0),
            "remaining_shares": int(40000000 / 40.0),
            "tag_id": 1,
        },
        {
            "name": "AMD",
            "symbol": "AMD",
            "description": "A competitor to Intel, AMD specializes in producing processors, GPUs, and high-performance computing solutions for gaming, enterprise, and cloud computing.",
            "price": 100.0,
            "initial_price": 100.0,
            "total_shares": int(50000000 / 100.0),
            "remaining_shares": int(50000000 / 100.0),
            "tag_id": 1,
        },
        {
            "name": "Ford",
            "symbol": "F",
            "description": "A long-established automobile manufacturer that produces a wide range of vehicles, including passenger cars, SUVs, trucks, and electric vehicles like the Mustang Mach-E.",
            "price": 20.0,
            "initial_price": 20.0,
            "total_shares": int(30000000 / 20.0),
            "remaining_shares": int(30000000 / 20.0),
            "tag_id": 2,
        },
        {
            "name": "General Motors",
            "symbol": "GM",
            "description": "A global automotive company producing brands like Chevrolet, Cadillac, and GMC. It focuses on sustainable technologies like electric and autonomous vehicles.",
            "price": 30.0,
            "initial_price": 30.0,
            "total_shares": int(35000000 / 30.0),
            "remaining_shares": int(35000000 / 30.0),
            "tag_id": 2,
        },
        {
            "name": "Boeing",
            "symbol": "BA",
            "description": "An aerospace leader manufacturing commercial airplanes, military aircraft, satellites, and space exploration technologies. It plays a crucial role in global aviation and defense.",
            "price": 200.0,
            "initial_price": 200.0,
            "total_shares": int(85000000 / 200.0),
            "remaining_shares": int(85000000 / 200.0),
            "tag_id": 6,
        },
        {
            "name": "Starbucks",
            "symbol": "SBUX",
            "description": "A premium coffeehouse chain that has become a global phenomenon, offering high-quality coffee, teas, and snacks, alongside a comfortable and social café experience.",
            "price": 100.0,
            "initial_price": 100.0,
            "total_shares": int(50000000 / 100.0),
            "remaining_shares": int(50000000 / 100.0),
            "tag_id": 4,
        },
        {
            "name": "Walmart",
            "symbol": "WMT",
            "description": "A retail giant known for offering affordable products across categories such as groceries, apparel, electronics, and more, both in-store and online through its extensive e-commerce operations.",
            "price": 150.0,
            "initial_price": 150.0,
            "total_shares": int(100000000 / 150.0),
            "remaining_shares": int(100000000 / 150.0),
            "tag_id": 7,
        },
        {
            "name": "Target",
            "symbol": "TGT",
            "description": "A popular retail chain known for its stylish and affordable products, offering everything from clothing and home goods to groceries and electronics, all with a focus on quality and design.",
            "price": 130.0,
            "initial_price": 130.0,
            "total_shares": int(70000000 / 130.0),
            "remaining_shares": int(70000000 / 130.0),
            "tag_id": 7,
        },
    ]

    for entry in stocks:
        stock = Stock(
            name=entry["name"],
            symbol=entry["symbol"],
            description=entry["description"],
            price=entry["price"],
            initial_price=entry["initial_price"],
            total_shares=entry["total_shares"],
            remaining_shares=entry["remaining_shares"],
            tag_id=entry["tag_id"],
        )
        db.session.add(stock)

    db.session.commit()
    print("Seeded stocks.")


def undo_stocks():
    if environment == "production":
        db.session.execute(text(f'TRUNCATE table "{SCHEMA}".stocks RESTART IDENTITY CASCADE;'))
    else:
        db.session.execute(text("DELETE FROM stocks"))
    db.session.commit()
    print("Undid stocks.")
