"""Add remaining_shares to stocks

Revision ID: 060d94b5cdca
Revises: 918c4d0f976c
Create Date: 2024-11-20 15:59:30.480770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060d94b5cdca'
down_revision = '918c4d0f976c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_shares', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('remaining_shares', sa.Integer(), nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_column('total_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_value', sa.INTEGER(), nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('remaining_shares')
        batch_op.drop_column('total_shares')

    # ### end Alembic commands ###
