stocks = [
    {"name": "Apple", "symbol": "AAPL", "description": "Tech giant", "price": 150.0, "total_value": 100000000, "tag_id": 1},
    {"name": "Tesla", "symbol": "TSLA", "description": "Electric vehicles", "price": 700.0, "total_value": 50000000, "tag_id": 2},
    {"name": "Amazon", "symbol": "AMZN", "description": "E-commerce leader", "price": 3300.0, "total_value": 150000000, "tag_id": 1},
    {"name": "Google", "symbol": "GOOGL", "description": "Search engine giant", "price": 2800.0, "total_value": 120000000, "tag_id": 1},
    {"name": "Microsoft", "symbol": "MSFT", "description": "Software and cloud", "price": 320.0, "total_value": 110000000, "tag_id": 1},
    {"name": "Meta", "symbol": "META", "description": "Social media leader", "price": 340.0, "total_value": 90000000, "tag_id": 1},
    {"name": "NVIDIA", "symbol": "NVDA", "description": "Graphics cards and AI", "price": 500.0, "total_value": 70000000, "tag_id": 1},
    {"name": "Netflix", "symbol": "NFLX", "description": "Streaming platform", "price": 400.0, "total_value": 60000000, "tag_id": 3},
    {"name": "Disney", "symbol": "DIS", "description": "Entertainment and media", "price": 120.0, "total_value": 80000000, "tag_id": 3},
    {"name": "Coca-Cola", "symbol": "KO", "description": "Beverage giant", "price": 60.0, "total_value": 60000000, "tag_id": 4},
    {"name": "PepsiCo", "symbol": "PEP", "description": "Food and beverage", "price": 150.0, "total_value": 65000000, "tag_id": 4},
    {"name": "Exxon Mobil", "symbol": "XOM", "description": "Oil and gas", "price": 110.0, "total_value": 100000000, "tag_id": 5},
    {"name": "Chevron", "symbol": "CVX", "description": "Energy corporation", "price": 130.0, "total_value": 95000000, "tag_id": 5},
    {"name": "Intel", "symbol": "INTC", "description": "Semiconductors", "price": 40.0, "total_value": 40000000, "tag_id": 1},
    {"name": "AMD", "symbol": "AMD", "description": "Microprocessors", "price": 100.0, "total_value": 50000000, "tag_id": 1},
    {"name": "Ford", "symbol": "F", "description": "Automobile manufacturer", "price": 20.0, "total_value": 30000000, "tag_id": 2},
    {"name": "General Motors", "symbol": "GM", "description": "Automotive company", "price": 30.0, "total_value": 35000000, "tag_id": 2},
    {"name": "Boeing", "symbol": "BA", "description": "Aerospace leader", "price": 200.0, "total_value": 85000000, "tag_id": 6},
    {"name": "Starbucks", "symbol": "SBUX", "description": "Coffeehouse chain", "price": 100.0, "total_value": 50000000, "tag_id": 4},
    {"name": "Walmart", "symbol": "WMT", "description": "Retail corporation", "price": 150.0, "total_value": 100000000, "tag_id": 7},
    {"name": "Target", "symbol": "TGT", "description": "Retail giant", "price": 130.0, "total_value": 70000000, "tag_id": 7},
]
